sonar.projectKey=ModalLK_payment-service
sonar.organization=shopix
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.language=java
sonar.sourceEncoding=UTF-8